# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-14 16:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fury', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='portfolio',
            old_name='user_id',
            new_name='user',
        ),
    ]
